/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Classes.Requisitos;
import Classes.*;
import java.sql.Connection;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;


public class FormProjetoAberto extends javax.swing.JFrame {

    Usuario usuario = new Usuario();
    Projeto projeto = new Projeto();
    Requisitos formReq;
    ConexaoBD conexao = new ConexaoBD();
    TableRowSorter trs;
    
    
    public FormProjetoAberto() {
        initComponents();
    
        /*
        formReq = new Requisitos();
        Vector listaReq = formReq.recuperarListaRequisitos(projeto.getId());

        Vector colunas = new Vector<>();

        colunas.add("id_requisito");
        colunas.add("nome");
        colunas.add("modulo");
        colunas.add("funcionalidades");
        colunas.add("dataCriacao");
        colunas.add("autor");
        colunas.add("dataAlteracao");
        colunas.add("autorAlteracao");
        colunas.add("versao");
        colunas.add("prioridade");
        colunas.add("complexidade");
        colunas.add("eforcoHoras");
        colunas.add("estado");
        colunas.add("fase");
        colunas.add("descricao");
        colunas.add("nome_projeto");
      
        DefaultTableModel dataModel = new DefaultTableModel();

        dataModel.setDataVector(listaReq, colunas);

        tbReq.setModel(dataModel);*/
  
        
    }

    public void Filtro(){
        int ColumnTable = 1; //Coluna Nome do Requistio
        trs.setRowFilter(RowFilter.regexFilter(jtxtFiltro.getText(),ColumnTable));
    }
    
    public void recebeTexto(String nomeProjeto){
        txfNomeProjAberto.setText(nomeProjeto);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo1 = new javax.swing.JLabel();
        btVoltarTelaInicial = new javax.swing.JButton();
        btInserirRequisito = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btMostrarTb = new javax.swing.JButton();
        jtxtFiltro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbReq = new javax.swing.JTable();
        txfNomeProjAberto = new javax.swing.JTextField();
        lbTitulo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CDR - Requisitos");

        lbTitulo1.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        lbTitulo1.setText(" Projeto:");

        btVoltarTelaInicial.setText("Voltar");
        btVoltarTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarTelaInicialActionPerformed(evt);
            }
        });

        btInserirRequisito.setText("Cadastrar");
        btInserirRequisito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirRequisitoActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btMostrarTb.setText("Gerar Relatorio");
        btMostrarTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarTbActionPerformed(evt);
            }
        });

        jtxtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFiltroActionPerformed(evt);
            }
        });
        jtxtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtFiltroKeyTyped(evt);
            }
        });

        jLabel2.setText("Filtrar:");

        tbReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbReqMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbReq);

        jScrollPane3.setViewportView(jScrollPane2);

        txfNomeProjAberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNomeProjAbertoActionPerformed(evt);
            }
        });

        lbTitulo2.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        lbTitulo2.setText("Requisitos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfNomeProjAberto, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btVoltarTelaInicial)
                        .addGap(118, 118, 118)
                        .addComponent(btInserirRequisito)
                        .addGap(61, 61, 61)
                        .addComponent(btEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExcluir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btMostrarTb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTitulo2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfNomeProjAberto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btMostrarTb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltarTelaInicial)
                    .addComponent(btInserirRequisito)
                    .addComponent(btExcluir)
                    .addComponent(btEditar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarTelaInicialActionPerformed
        FormGerenciarProjeto formGerenciarProjeto = new FormGerenciarProjeto();

        formGerenciarProjeto.setVisible(true);
        formGerenciarProjeto.usuario = usuario;

        setVisible(false);
    }//GEN-LAST:event_btVoltarTelaInicialActionPerformed

    private void btInserirRequisitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirRequisitoActionPerformed
            FormInserirRequisito telaReq = new FormInserirRequisito();
            
            telaReq.proj=projeto;
            telaReq.usuario=usuario;
            
            
            telaReq.setVisible(true);
            
    }//GEN-LAST:event_btInserirRequisitoActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
            Requisitos req = new Requisitos();
        
        if (tbReq.getSelectedRow() != -1){

            
            req.setId((int)tbReq.getValueAt(tbReq.getSelectedRow(), 0));


            req.excluirRequisito(req.getId());
            

        } else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir");
        }
       
    }//GEN-LAST:event_btExcluirActionPerformed

    private void tbReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbReqMouseClicked

    }//GEN-LAST:event_tbReqMouseClicked

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        FormEditarRequisito telaEditar = new FormEditarRequisito();
        if (tbReq.getSelectedRow() != -1){

            telaEditar.req.setId((int)tbReq.getValueAt(tbReq.getSelectedRow(), 0));
 
            telaEditar.usuario = usuario;
            telaEditar.proj = projeto;
            
            
            telaEditar.setVisible(true);
            
        } else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha.");
        }
       
        
    }//GEN-LAST:event_btEditarActionPerformed

    private void btMostrarTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarTbActionPerformed
            
      
        formReq = new Requisitos();
        Vector listaReq = formReq.recuperarListaRequisitos(projeto.getId());

        Vector colunas = new Vector<>();

        colunas.add("id_requisito");
        colunas.add("nome");
        colunas.add("modulo");
        colunas.add("funcionalidades");
        colunas.add("dataCriacao");
        colunas.add("autor");
        colunas.add("dataAlteracao");
        colunas.add("autorAlteracao");
        colunas.add("versao");
        colunas.add("prioridade");
        colunas.add("complexidade");
        colunas.add("eforcoHoras");
        colunas.add("estado");
        colunas.add("fase");
        colunas.add("descricao");
        colunas.add("id_projeto");
      
        DefaultTableModel dataModel = new DefaultTableModel();

        dataModel.setDataVector(listaReq, colunas);

        tbReq.setModel(dataModel);
  
    

    }//GEN-LAST:event_btMostrarTbActionPerformed

    private void jtxtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFiltroActionPerformed


    private void jtxtFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtFiltroKeyTyped
        
        jtxtFiltro.addKeyListener(new KeyAdapter(){
            
            public void keyReleased(final KeyEvent e){
                String texto = (jtxtFiltro.getText());
                jtxtFiltro.setText(texto);
                Filtro();
            }
        });

        trs = new TableRowSorter(tbReq.getModel());
        tbReq.setRowSorter(trs);
    }//GEN-LAST:event_jtxtFiltroKeyTyped

    private void txfNomeProjAbertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNomeProjAbertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNomeProjAbertoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProjetoAberto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProjetoAberto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProjetoAberto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProjetoAberto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProjetoAberto().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInserirRequisito;
    private javax.swing.JButton btMostrarTb;
    private javax.swing.JButton btVoltarTelaInicial;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jtxtFiltro;
    private javax.swing.JLabel lbTitulo1;
    private javax.swing.JLabel lbTitulo2;
    private javax.swing.JTable tbReq;
    private javax.swing.JTextField txfNomeProjAberto;
    // End of variables declaration//GEN-END:variables
}
