/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Classes.Usuario;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FormGerenciarUsuario extends javax.swing.JFrame {
    
    Usuario usuarioForm;
    Usuario usuario = new Usuario();
    
    private String nomeUsuario;

    public String getNomeUsuario() {
        return nomeUsuario;
    }

    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }
      
    /**
     * Creates new form FormGerenUsuario
     */
    public FormGerenciarUsuario() {
           
        initComponents();
        usuarioForm = new Usuario();
        Vector listaUsuarios = usuarioForm.recuperarListaUsuarios();
        
        Vector colunas = new Vector<>();
   
        colunas.add("id");
        colunas.add("nome_completo");
        colunas.add("email");
        colunas.add("telefone");
        colunas.add("nome_usuario");
        colunas.add("senha");
               
        DefaultTableModel dataModel = new DefaultTableModel();
        
        dataModel.setDataVector(listaUsuarios, colunas);
        
        tblUsuarios.setModel(dataModel);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btVoltarTelaInicial = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluirUsuario = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        btnAtualizarTabelaUsuario = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        lbNome = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        txfNomeCompleto = new javax.swing.JTextField();
        txfEmailUsuario = new javax.swing.JTextField();
        passSenha = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        lbNomeUsuario = new javax.swing.JLabel();
        txfNomeUsuario = new javax.swing.JTextField();
        txfTelefone = new javax.swing.JTextField();
        lbSenha1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CDR - Requisitos");

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nome_completo", "email", "telefone", "nome_usuario", "senha"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        jScrollPane2.setViewportView(jScrollPane1);

        btVoltarTelaInicial.setText("Voltar");
        btVoltarTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarTelaInicialActionPerformed(evt);
            }
        });

        btnEditar.setText("Salvar Alteração");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluirUsuario.setText("Excluir");
        btnExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUsuarioActionPerformed(evt);
            }
        });

        lbTitulo.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        lbTitulo.setText("Usuários");

        btnAtualizarTabelaUsuario.setText("Atualizar Lista");
        btnAtualizarTabelaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarTabelaUsuarioActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        lbNome.setText("Nome:");

        lbEmail.setText("Email:");

        lbSenha.setText("Telefone");

        txfNomeCompleto.setToolTipText("");
        txfNomeCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNomeCompletoActionPerformed(evt);
            }
        });

        txfEmailUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfEmailUsuarioActionPerformed(evt);
            }
        });

        passSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passSenhaActionPerformed(evt);
            }
        });

        lbNomeUsuario.setText("Nome de Usuario:");

        txfTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfTelefoneActionPerformed(evt);
            }
        });

        lbSenha1.setText("Senha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEmail, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txfNomeCompleto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txfEmailUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btVoltarTelaInicial)
                        .addGap(48, 48, 48)
                        .addComponent(btCadastrar)
                        .addGap(89, 89, 89)
                        .addComponent(btnExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNomeUsuario)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lbSenha1)))
                        .addGap(11, 11, 11))
                    .addComponent(txfNomeUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAtualizarTabelaUsuario)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(lbTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAtualizarTabelaUsuario)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNome)
                            .addComponent(txfNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEmail)
                            .addComponent(txfEmailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSenha)
                            .addComponent(txfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNomeUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lbSenha1))
                            .addComponent(txfNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltarTelaInicial)
                    .addComponent(btnExcluirUsuario)
                    .addComponent(btCadastrar)
                    .addComponent(btnEditar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarTelaInicialActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btVoltarTelaInicialActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        if (tblUsuarios.getSelectedRow() != -1){
            
            usuario.setNomeCompleto(txfNomeCompleto.getText());
            usuario.setEmail(txfEmailUsuario.getText());
            usuario.setTelefone(Integer.parseInt(txfTelefone.getText()));
            usuario.setNomeUsuario(txfNomeUsuario.getText());
            usuario.setSenha(passSenha.getText());

            usuario.setId((int)tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(),0));
            
            
        if(usuario.getNomeCompleto().length()==0){
            JOptionPane.showMessageDialog(null,"O campo nome está vazio");
        }else if(usuario.getEmail().length()==0){
            JOptionPane.showMessageDialog(null,"O campo email está vazio");
        }else if(usuario.getSenha().length()<=3){
            JOptionPane.showMessageDialog(null,"O campo senha está preenchido errado");
        }else if(usuario.getNomeUsuario().length()==0){
            JOptionPane.showMessageDialog(null,"O campo nome de usuario está vazio");
        }else if(usuario.getTelefone()<=0){
            JOptionPane.showMessageDialog(null,"O campo telefone está vazio");
        }else {
            usuario.editarUsuario(usuario);
        }
         
            txfNomeCompleto.setText("");
            txfNomeUsuario.setText("");
            passSenha.setText("");
            txfTelefone.setText("");
            txfEmailUsuario.setText("");
            
        

            
        }    
  

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuarioActionPerformed
            
        if (tblUsuarios.getSelectedRow() != -1){
            
            usuario.setId((int)tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 0));

            usuario.deletarUsuario(usuario);
           
            txfNomeCompleto.setText("");
            txfNomeUsuario.setText("");
            passSenha.setText("");
            txfTelefone.setText("");
            txfEmailUsuario.setText("");
            
        } else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para excluir");
        }
    }//GEN-LAST:event_btnExcluirUsuarioActionPerformed

    private void btnAtualizarTabelaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarTabelaUsuarioActionPerformed
        
        usuarioForm = new Usuario();
        Vector listaUsuarios = usuarioForm.recuperarListaUsuarios();
        
        Vector colunas = new Vector<>();
   
        colunas.add("id");
        colunas.add("nome_completo");
        colunas.add("email");
        colunas.add("telefone");
        colunas.add("nome_usuario");
        colunas.add("senha");
               
        DefaultTableModel dataModel = new DefaultTableModel();
        
        dataModel.setDataVector(listaUsuarios, colunas);
        
        tblUsuarios.setModel(dataModel);
 
        
        
    }//GEN-LAST:event_btnAtualizarTabelaUsuarioActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        if(tblUsuarios.getSelectedRow() != -1){

            txfNomeCompleto.setText(tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 1).toString());
            txfEmailUsuario.setText(tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 2).toString());
            txfTelefone.setText(tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 3).toString());
            txfNomeUsuario.setText(tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 4).toString());
            passSenha.setText(tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 5).toString());

            
        }        
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        Usuario usuario = new Usuario();

        usuario.setNomeCompleto(txfNomeCompleto.getText());
        usuario.setEmail(txfEmailUsuario.getText());
        usuario.setSenha(passSenha.getText());
        usuario.setNomeUsuario(txfNomeUsuario.getText());
        usuario.setTelefone(Integer.parseInt(txfTelefone.getText()));

        if(usuario.getNomeCompleto().length()==0){
            JOptionPane.showMessageDialog(null,"O campo nome está vazio");
        }else if(usuario.getEmail().length()==0){
            JOptionPane.showMessageDialog(null,"O campo email está vazio");
        }else if(usuario.getSenha().length()<=3){
            JOptionPane.showMessageDialog(null,"O campo senha está preenchido errado");
        }else if(usuario.getNomeUsuario().length()==0){
            JOptionPane.showMessageDialog(null,"O campo nome de usuario está vazio");
        }else if(usuario.getTelefone()<=0){
            JOptionPane.showMessageDialog(null,"O campo telefone está vazio");
        }else {
            usuario.inserirUsario();
        }
        
        txfNomeCompleto.setText("");
        txfNomeUsuario.setText("");
        passSenha.setText("");
        txfTelefone.setText("");
        txfEmailUsuario.setText("");

    }//GEN-LAST:event_btCadastrarActionPerformed

    private void txfNomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNomeCompletoActionPerformed

    }//GEN-LAST:event_txfNomeCompletoActionPerformed

    private void txfEmailUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfEmailUsuarioActionPerformed

    }//GEN-LAST:event_txfEmailUsuarioActionPerformed

    private void passSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passSenhaActionPerformed

    }//GEN-LAST:event_passSenhaActionPerformed

    private void txfTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGerenciarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btVoltarTelaInicial;
    private javax.swing.JButton btnAtualizarTabelaUsuario;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluirUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomeUsuario;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbSenha1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPasswordField passSenha;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txfEmailUsuario;
    private javax.swing.JTextField txfNomeCompleto;
    private javax.swing.JTextField txfNomeUsuario;
    private javax.swing.JTextField txfTelefone;
    // End of variables declaration//GEN-END:variables
}
